### ISSUE TITLE
Question: use environment variables in `digital_editions.yml`

### ISSUE THREAD

**Issue by omBratteng** [slsfi/digital_edition_api#27]
Is it possible to use environment variables in the `digital_editions.yml` config?
Specifically the parts including passwords.

**Comment by rasek-sls** [comment]
This is not currently possible, though it could be added.

However, the parsing would have to be done in code, YAML itself doesn't support arbitrary env variable substitution - I'll look at making both $ENV and ${ENV} work properly.

**Comment by rasek-sls** [comment]
Environment variables are now fully supported in config files.

**Comment by omBratteng** [comment]
Awesome. I solved it another way through the docker image by using an entrypoint file and envsubst.
But this'll work too.
